# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9DSYvpQjjF2voTWfUbJs1G_VnAX-wNJ
"""

import pandas as pd

baza = {
    "FISH": ["Yusupov Dilyorbek", "Nabijonov Maqasadjon", "Jakbajaliyev Javlonbek", "Xonqulov Muhammadjon", "Yusupova Sarvinoz", "Qo'shmaqova Gulzoda"],
    "Yoshi": [19, 20, 25, 24, 21, 26],
    "Manzili": ["Qo'qon", "Farg'ona", "Andijon", "Namangan", "Toshkent", "Farg'ona"],
    "Jinsi": ["erkak", "erkak", "erkak", "erkak", "ayol", "ayol"],
    "Ish joyi": ["TATUFF", "FARDU", "ADU", "FARPI", "DXX", "TATUFF"]
}

db = pd.DataFrame(baza)
db.to_excel('614.xlsx', index=False)  # Corrected the method name and file extension
print(db)

filtr=db[db['Jinsi']=='erkak']
print(filtr)

filtr=db[(db['Jinsi']=='erkak') & (db['Ish joyi']=='TATUFF') & (db['Yoshi']<'23')]
print(filtr)

filtr=db[db['Jinsi']=='ayol']
print(filtr)